training:
  lr: 0.01
  num_classes: 5
  metric: val_loss
  seed: ${seed}
  job_name: ${run_name}
  checkpoint_path: ${checkpoint_path}
  model_save_dir: ${model_save_dir}
  num_epochs: 10
  image_dim: 224
  dataloaders:
    batch_size: 128
    pin_memory: true
    num_workers: 5
