training:
  lr: 0.01
  num_classes: 5
  metric: val_loss
  seed: 42
  job_name: default
  checkpoint_path: /kaggle/working/
  model_save_dir: /kaggle/working/model_weights.pt
  num_epochs: 10
  image_dim: 224
  dataloaders:
    batch_size: 128
    pin_memory: true
    num_workers: 5
